version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}


services:
  django: &django
    build:
      context: ./store/
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./ecommerce:/app
    environment:
      - POSTGRES_USER=ecommerce
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh
  
  postgres:
    build:
      context: ./store/
      dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=ecommerce

  redis:
    image: redis:3.0

  celeryworker:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat.sh
  