# Generated by Django 2.1.1 on 2018-12-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
